[package]
name = "serde-encrypted-value"
version = "0.1.1"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "Apache-2.0"
description = "A Serde Deserializer wrapper which transparently decrypts encrypted values"
repository = "https://github.com/palantir/serde-encrypted-value"
documentation = "https://docs.rs/serde-encrypted-value/0.1.0/serde_encrypted_value"
readme = "README.md"

[dependencies]
base64 = "0.3"
error-chain = "0.8"
openssl = "0.9"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dev-dependencies]
tempdir = "0.3"
